name: "Install without cache"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ["3.9", "3.10"]
        pytorch-version: ["1.11.0", "1.12.0"]
        exclude:
          - {os: "windows-latest", python-version: "3.9", pytorch-version: "1.11.0"}
          - {os: "windows-latest", python-version: "3.10", pytorch-version: "1.12.0"}
        # we can only run 20 concurrent jobs, so each of the two workflow files must only lunch 10 actions
        # 3 (number of os) x 2 (number of python versions) x 2 (number of pytorch version) - 2 (excluded) = 10

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==${{ matrix.pytorch-version }}
        pip install -r requirements.txt